version: '3.3'

volumes:
  static_value:
  media_value:
  frontend_value:
  pg_data:
  redoc:

services:

  db:
    image: postgres:13.10
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  
  backend:
    image: trieste/foodgram_backend
    restart: always
    depends_on:
        - db
    env_file:
        - ./.env
    volumes:
      - static_value:/backend_static/
      - media_value:/media/

  frontend:
    image: trieste/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - frontend_value:/app/build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend
    restart: always
