# Generated by Django 3.2.15 on 2023-10-21 11:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20231011_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsinrecipe',
            options={'verbose_name': 'Ингредиенты для рецептов', 'verbose_name_plural': 'Ингредиенты для рецептов'},
        ),
        migrations.AlterModelOptions(
            name='tagsinrecipe',
            options={'verbose_name': 'Тэги для рецептов', 'verbose_name_plural': 'Тэги для рецептов'},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='users.user', verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Изображение блюда'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#([a-fA-F0-9]{6})', message='Поле должно содержать HEX-код выбранного цвета.')], verbose_name='Цвет тега'),
        ),
        migrations.AddConstraint(
            model_name='ingredientsinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredientsinrecipes'),
        ),
        migrations.AddConstraint(
            model_name='tagsinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_tagsinrecipes'),
        ),
    ]
